# Generated by Django 4.2.17 on 2025-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.CharField(default='exp', max_length=50),
        ),
    ]
